### ISSUE TITLE
get or apply not working

### ISSUE THREAD

**Issue by clemenko** [hobbyfarm/hfcli#3]
I am using the latest `hfcli` and I am not able to `get` or `apply` any scenarios.

```bash
# info for the admin account
clembookpro:clemenko barn ( 54.210.145.222:6443 ) $ ./hfcli -k ~/.kube/config -n hobbyfarm info email admin
SESSION  | VMID  | STATUS  | PUBLICIP  |

# get a scenario
clembookpro:clemenko barn ( 54.210.145.222:6443 ) $ ./hfcli -k ~/.kube/config -n hobbyfarm get scenario rgs-workshop Rodeos/rgs 
INFO[0000] rgs-workshopRodeos/rgs                       
INFO[0000] downloading scenario rgs-workshop            
FATA[0000] the server could not find the requested resource (get scenarios.hobbyfarm.io rgs-workshop) 

# scenario is there
clembookpro:clemenko barn ( 54.210.145.222:6443 ) $ kubectl  get scenarios -A
NAMESPACE   NAME           AGE
hobbyfarm   rgs-workshop   12m


# apply
clembookpro:clemenko barn ( 54.210.145.222:6443 ) $ ./hfcli -k ~/.kube/config -n hobbyfarm apply scenario git-maintained-rodeo-neuvector Rodeos/NeuVector/
INFO[0000] git-maintained-rodeo-neuvectorRodeos/NeuVector/ 
INFO[0000] creating scenario git-maintained-rodeo-neuvector 
FATA[0000] the server could not find the requested resource (post scenarios.hobbyfarm.io) 

```

what am I doing wrong?

**Comment by caylorme** [comment]
Hey @clemenko,

I submitted a PR for this project which resolves an issue with the tool not having the ability to pass the namespace string into the underlying API calls.

https://github.com/hobbyfarm/hfcli/pull/4

If you could, use this patch and let me know if this resolves your issue.

**Comment by clemenko** [comment]
Do you by chance have a MacOS Arm binary?

**Comment by caylorme** [comment]
~~[hfcli-darwin-arm64.zip](https://github.com/hobbyfarm/hfcli/files/13300599/hfcli-darwin-arm64.zip)
@clemenko, I compiled this for darwin/arm64 from my dev machine (untested).~~

It looks like the PR got merged, so the release is available: https://github.com/hobbyfarm/hfcli/releases/download/v0.2.0/hfcli_Darwin_arm64.tar.gz

**Comment by clemenko** [comment]
Looks like it is working. Thanks
